import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google"
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["vietnamese"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "მთავარია გქონდეს ფული, რომ არ იყო დაჩაგრული",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center mt-32 min-h-[calc(screen-32rem]`}
    >
      <Providers>
        <Header />
        <main className='container'>
            {children}
        </main>
        {/*<Footer />*/}
      </Providers>
    </body>
    </html>
  );
}
